# fly.toml app configuration file generated for markmark-bot on 2024-04-20T06:57:49+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'markmark-bot'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[processes]
app = 'run --allow-env --allow-net --allow-read ./bot.ts'

[[vm]]
memory = '500mb'
cpu_kind = 'shared'
cpus = 1
